version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: infra/api.dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
  ui:
    build:
      context: .
      dockerfile: infra/ui.dockerfile
      args:
        API_ENDPOINT: http://localhost:8080/graphql
    env_file:
      - .env
    ports:
      - 3000:80
  db:
    image: postgres:15.4-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres: