version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: infra/api.dockerfile
    ports:
      - 8080:8080
  db:
    image: postgres:15.4-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres: