version: '3'

dotenv:
  - .env

env:
  DATABASE_URL: postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:5432/{{.DB_NAME}}?sslmode=disable
  DBMATE_MIGRATIONS_DIR: internal/db/migrations

tasks:
  setup:
    deps:
      - api.install
      - ui.install

  sqlc:
    cmds:
      - sqlc generate

  gql:
    cmds:
      - go run github.com/99designs/gqlgen generate

  generate:
    deps: [sqlc, gql]
    cmds:
      - go generate ./internal/...

  up:
    cmds:
      - docker-compose up

  down:
    cmds:
      - docker-compose down {{ .CLI_ARGS }}

  db:
    cmds:
      - docker-compse up db

  api.install:
    cmds:
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/vektra/mockery/v2@v2.32.4

  api.dev:
    cmds:
      - go run cmd/api/main.go

  api.build:
    cmds:
      - go build -o build/api cmd/api/main.go

  db.migrate.up:
    cmds:
      - npx dbmate up

  db.migrate.down:
    cmds:
      - npx dbmate down

  ui.install:
    dir: ui
    cmds:
      - npm i