// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: genres.sql

package db

import (
	"context"

	"github.com/gofrs/uuid"
)

const createGenreForUser = `-- name: CreateGenreForUser :one
INSERT INTO genres (
  "name",
  "user"
) VALUES (
  $1, $2
)
RETURNING id, "user", name
`

type CreateGenreForUserParams struct {
	Name string
	User uuid.UUID
}

func (q *Queries) CreateGenreForUser(ctx context.Context, arg CreateGenreForUserParams) (Genre, error) {
	row := q.db.QueryRow(ctx, createGenreForUser, arg.Name, arg.User)
	var i Genre
	err := row.Scan(&i.ID, &i.User, &i.Name)
	return i, err
}

const getUserGenres = `-- name: GetUserGenres :many
SELECT id, "user", name from genres
WHERE "user" = $1
ORDER BY "name" ASC
`

func (q *Queries) GetUserGenres(ctx context.Context, user uuid.UUID) ([]Genre, error) {
	rows, err := q.db.Query(ctx, getUserGenres, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.User, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
