// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"

	"github.com/gofrs/uuid"
)

type Movie struct {
	ID         uuid.UUID
	Title      string
	Rating     string
	Genre      string
	Cast       []string
	Director   string
	Poster     sql.NullString
	User       uuid.UUID
	UserRating sql.NullInt32
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	CreatedAt time.Time
	DeletedAt sql.NullTime
	LastLogin time.Time
}
