// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: movies.sql

package db

import (
	"context"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AddMovieGenresParams struct {
	Movie uuid.UUID
	Genre uuid.UUID
}

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (
  "title",
  "rating",
  "cast",
  "director",
  "poster",
  "user_rating",
  "user"
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, title, rating, "cast", director, poster, "user", user_rating
`

type CreateMovieParams struct {
	Title      string
	Rating     string
	Cast       []string
	Director   string
	Poster     pgtype.Text
	UserRating pgtype.Int4
	User       uuid.UUID
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.Title,
		arg.Rating,
		arg.Cast,
		arg.Director,
		arg.Poster,
		arg.UserRating,
		arg.User,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Rating,
		&i.Cast,
		&i.Director,
		&i.Poster,
		&i.User,
		&i.UserRating,
	)
	return i, err
}

const getMovieGenres = `-- name: GetMovieGenres :many
SELECT genres.id, genres."user", genres.name FROM genres
INNER JOIN movie_genres mg ON mg.genre = genres.id
WHERE mg.movie = $1
ORDER BY genres.name ASC
`

func (q *Queries) GetMovieGenres(ctx context.Context, movie uuid.UUID) ([]Genre, error) {
	rows, err := q.db.Query(ctx, getMovieGenres, movie)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.User, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
